### PR TITLE
Mataro / Update Debt

### PR DESCRIPTION
**Pull request by jbb231**
Closes [#1809](https://github.com/PopulateTools/issues/issues/1809)

## :v: What does this PR do?
Updates the three URLs with the new datasets. 

## Considerations:
There are some minor differences between previous files and updated files: 

1. '01_Deute_Total_Deutor 2022 - 01_Deute_Total_Deutor 2022.csv': 
    - New raw: 'AJUNTAMENT - PENDENT RETORN PIE LIQ. NEGATIVA 2020'
    -  'CONSORCI TR. RESIDUS' value is equal to zero.
2. '02_Deute_Entitat_Creditora 2022 - 02_Deute_Entitat_Creditora 2022.csv':
    - New row: Bankinter
3. '03_evolucio_endeutament_GRUP AJUNTAMENT 2022 - 03_evolucio_endeutament_GRUP AJUNTAMENT 2022.csv':
    - 'any' row without name.

### CODE REVIEW

**Comment by jbb231** [comment]
I think the minor differences between the new and previous files do not have impact because the columns order remains the same. But where can I check the structure of the tables to confirm?

**Comment by furilo** [comment]
@jorgeatgu is any change needed in https://mataro.gobify.net/visualizaciones/costes so that the data appears?

**Comment by ferblape** [comment]
Screenshot 2023-03-28 at 10 42 28

If you check the datasets at https://mataro.gobify.net/datos it seems that only one of the three datasets has been updated (check the updated dates). Could you confirm by checking the log in Jenkins @jbb231 ?

**Comment by jbb231** [comment]
I haven't merge the branch yet in staging because I was waiting to confirm that the structure is correct. No dataset is updated. But I'll do it now.

**Comment by jbb231** [comment]
Now it's merged into staging and datasets updated. I have modified the names of columns that where creating conflicts in files 2 and 3.

**Review by jorgeatgu — APPROVED** [review]

**Comment by jbb231** [comment]
Now this branch is merged into master and updated in jenkins production.

**Pull request merged**
